Panda86\AdminBundle\Entity\User:
    type: entity
    table: hr_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
            length: '64'
        last_name:
            type: string
            length: '64'
        username:
            type: string
            length: '16'
        password:
            type: string
            length: '10'
        salt:
            type: string
            length: '16'
        is_admin:
            type: boolean
            length: null
        is_manager:
            type: boolean
            length: null
        email:
            type: string
            length: '32'
    lifecycleCallbacks: {  }
