Panda86AppBundle_vehicle:
        resource: "@Panda86AppBundle/Resources/config/routing/vehicle.yml"
        prefix:   /s/vehicle

Panda86AppBundle_vtype:
        resource: "@Panda86AppBundle/Resources/config/routing/vtype.yml"
        prefix:   /s/vtype

Panda86AppBundle_driver:
        resource: "@Panda86AppBundle/Resources/config/routing/driver.yml"
        prefix:   /s/driver

Panda86AppBundle_approve:
        resource: "@Panda86AppBundle/Resources/config/routing/approve.yml"
        prefix:   /a/approve

Panda86AppBundle_disapprove:
      resource: "@Panda86AppBundle/Resources/config/routing/disapprove.yml"
      prefix:   /a/disapprove

Panda86AppBundle_request:
        resource: "@Panda86AppBundle/Resources/config/routing/request.yml"
        prefix:   /a/request

Panda86AppBundle_report:
        resource: "@Panda86AppBundle/Resources/config/routing/report.yml"
        prefix:   /s/report

