admin_home:
    pattern:  /admin
    defaults: { _controller: Panda86AppBundle:Home:index }

Panda86AppBundle_vtype:
        resource: "@Panda86AppBundle/Resources/config/routing/vtype.yml"
        prefix:   /vtype

Panda86AppBundle_vehicle:
        resource: "@Panda86AppBundle/Resources/config/routing/vehicle.yml"
        prefix:   /vehicle

Panda86AppBundle_driver:
        resource: "@Panda86AppBundle/Resources/config/routing/driver.yml"
        prefix:   /driver

Panda86AppBundle_request:
        resource: "@Panda86AppBundle/Resources/config/routing/request.yml"
        prefix:   /request
