app_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

panda86_user_bundle:
    resource: "@Panda86UserBundle/Resources/config/routing.yml"
    prefix:   /

panda86_app_bundle:
    resource: "@Panda86AppBundle/Resources/config/routing.yml"
    prefix:   /

Panda86AppBundle_public:
      resource: "@Panda86AppBundle/Resources/config/routing/public.yml"
      prefix:   /u/request

#Acme_sandbox_bundle:
#    resource: "@AcmeSandboxBundle/Resources/config/routing/sandbox.yml"
#    prefix:   /
