app_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

admin_login:
    path:     /admin/login
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true

panda86_admin:
    resource: "@Panda86UserBundle/Resources/config/routing.yml"
    prefix:   /

panda86_vehicle:
        resource: "@Panda86UserBundle/Resources/config/routing/vehicle.yml"
        prefix:   /vehicle

panda86_request:
        resource: "@Panda86UserBundle/Resources/config/routing/request.yml"
        prefix:   /request

Panda86UserBundle_driver:
        resource: "@Panda86UserBundle/Resources/config/routing/driver.yml"
        prefix:   /driver

Panda86UserBundle_user:
        resource: "@Panda86UserBundle/Resources/config/routing/user.yml"
        prefix:   /
