app_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

admin_login:
    path:     /admin/login
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true

panda86_admin:
    resource: "@Panda86UserBundle/Resources/config/routing.yml"
    prefix:   /

panda86_app:
    resource: "@Panda86AppBundle/Resources/config/routing.yml"
    prefix:   /

# sandbox routes
AcmeSandboxBundle_sandbox:
        resource: "@AcmeSandboxBundle/Resources/config/routing/sandbox.yml"
        prefix:   /
