app_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true

admin_login:
    path:     /admin/login
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true

panda86_admin:
    resource: "@Panda86UserBundle/Resources/config/routing.yml"
    prefix:   /
