security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ANONYMOUS:
        ROLE_USER:        ROLE_ANONYMOUS
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
            logout:
                path:   /logout
                target: /login
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # public access
        - { path: ^/app, roles: IS_AUTHENTICATED_ANONYMOUSLY } # public access
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY } # debug toolbar
        - { path: ^/s, roles: ROLE_SUPER_ADMIN } # super admin access
        - { path: ^/a, roles: ROLE_ADMIN } # admin access
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY } # public access
