parameters:
#    panda86_admin.example.class: Panda86\AdminBundle\Example

services:
#    panda86_admin.example:
#        class: %panda86_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
