Panda86\AppBundle\Entity\ApprovedCab:
    type: entity
    table: vrm_approved_cab
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        voucher_no:
            type: string
            length: '64'
            nullable: true
        mileage:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        rate:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        cost:
            type: decimal
            precision: 7
            scale: 2
            nullable: true
        other_info:
            type: string
            length: '255'
            nullable: true
    manyToOne:
        cab_service:
          targetEntity: CabService
          joinColumn:
              name: cab_service_id
              nullable: false
              referencedColumnName: id
    lifecycleCallbacks: {  }
