Panda86\AppBundle\Entity\Driver:
    type: entity
    table: vrm_driver
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:      
        first_name:
            type: string
            length: '64'
        last_name:
            type: string
            length: '64'
        display_name:
            type: string
            length: '64'
            nullable: true
        birth_date:
            type: date            
        license_date:
            type: date
        license_ref:
            type: string
            length: '64'
        address:
            type: string
            length: '255'    
        mobile:
            type: integer
            length: 20
        image:
            type: string
            length: '255'
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
    lifecycleCallbacks: {  }
