Panda86\AppBundle\Entity\Report:
    type: entity
    table: vrm_report
    repositoryClass: Panda86\AppBundle\Entity\ReportRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        report:
            type: text
    lifecycleCallbacks: {  }
