Panda86\AppBundle\Entity\Request:
    type: entity
    table: hr_request
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        journey_type:
            type: string
            length: '64'
        days:
            type: integer
            nullable: true
        pickup_loc:
            type: string
            length: '64'
            column: pickup_loc
        pickup_time:
            type: datetime
            column: pickup_time
        destination:
            type: string
            length: '64'
        return_time:
            type: datetime
            column: return_time
        purpose:
            type: string
            length: '64'
        created_at:
            type: datetime
        updated_at:
            type: datetime
    manyToOne:
        vtype:
            targetEntity: VType
            inversedBy: vehicles
            joinColumn:
                name: vtype_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
