user_index:
    pattern:  /
    defaults: { _controller: Panda86UserBundle:User:index }
    requirements: { _method: get }

user_show:
    pattern:  /{id}/profile
    defaults: { _controller: Panda86UserBundle:User:show }
    requirements: { _method: get }

user_new:
    pattern:  /new
    defaults: { _controller: Panda86UserBundle:User:new }

user_create:
    pattern:  /create
    defaults: { _controller: Panda86UserBundle:User:create }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: Panda86UserBundle:User:edit }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: Panda86UserBundle:User:delete }
    requirements: { _method: post|delete }
