user_index:
    pattern:  /
    defaults: { _controller: Panda86UserBundle:User:index }
    requirements: { _method: get }

user_show:
    pattern:  /{id}/profile
    defaults: { _controller: Panda86UserBundle:User:show }
    requirements: { _method: get }

user_new:
    pattern:  /new
    defaults: { _controller: Panda86UserBundle:User:new }

user_create:
    pattern:  /new
    defaults: { _controller: Panda86UserBundle:User:create }
    requirements: { _method: post }

user_remove:
    pattern:  /{id}/remove
    defaults: { _controller: Panda86UserBundle:User:remove }
    requirements: { _method: delete }
