fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


admin_home:
    pattern:  /admin
    defaults: { _controller: Panda86UserBundle:Default:index }

user_index:
    pattern:  /admin/user
    defaults: { _controller: Panda86UserBundle:User:index }

user_create:
    pattern:  /admin/user/create
    defaults: { _controller: Panda86UserBundle:User:create }

user_profile:
    pattern:  /admin/user/{id}/profile
    defaults: { _controller: Panda86UserBundle:User:show }

user_remove:
    pattern:  /admin/user/{id}/remove
    defaults: { _controller: Panda86UserBundle:User:remove }


request_new:
    pattern:  /request/new
    defaults: { _controller: Panda86UserBundle:Request:new }

request_submit:
    pattern:  /request/submit
    defaults: { _controller: Panda86UserBundle:Request:submit }

request_success:
    pattern:  /request
    defaults: { _controller: Panda86UserBundle:Request:index }