Panda86\UserBundle\Entity\Request:
    properties:
        requested_for:
            - NotBlank: ~
        end_loc:
            - NotBlank: ~
        purpose:
            - NotBlank: ~
#        start_time:
#            - Type: \DateTime
#        pickup_time:
#            - Type: \DateTime
#        end_time:
#            - Type: \DateTime