approve_new:
    pattern:  /new/{req_id}
    defaults: { _controller: "Panda86AppBundle:Approve:new" }

approve_create:
    pattern:  /create
    defaults: { _controller: "Panda86AppBundle:Approve:create" }
    requirements: { _method: post }