disapprove:
    pattern:  /
    defaults: { _controller: "Panda86AppBundle:Disapprove:index" }

disapprove_show:
    pattern:  /{id}/show
    defaults: { _controller: "Panda86AppBundle:Disapprove:show" }

disapprove_new:
    pattern:  /new/{req_id}
    defaults: { _controller: "Panda86AppBundle:Disapprove:new" }

disapprove_create:
    pattern:  /create
    defaults: { _controller: "Panda86AppBundle:Disapprove:create" }
    requirements: { _method: post }
