report_index:
    pattern: /
    defaults: { _controller: "Panda86AppBundle:Report:index" }

report_generate:
    pattern: /{type}/generate
    defaults: { _controller: "Panda86AppBundle:Report:generate" }

report_download:
    pattern: /{format}/download
    defaults: { _controller: "Panda86AppBundle:Report:download" }