request:
    pattern:  /
    defaults: { _controller: "Panda86AppBundle:Request:index" }

request_show:
    pattern:  /{id}/show
    defaults: { _controller: "Panda86AppBundle:Request:show" }

request_new:
    pattern:  /new
    defaults: { _controller: "Panda86AppBundle:Request:new" }

request_create:
    pattern:  /create
    defaults: { _controller: "Panda86AppBundle:Request:create" }
    requirements: { _method: post }

request_finish:
    pattern:  /finish
    defaults: { _controller: "Panda86AppBundle:Request:finish" }

request_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "Panda86AppBundle:Request:edit" }

request_update:
    pattern:  /{id}/update
    defaults: { _controller: "Panda86AppBundle:Request:update" }
    requirements: { _method: post|put }

request_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "Panda86AppBundle:Request:delete" }
    requirements: { _method: post|delete }
