Acme\SandboxBundle\Entity\Task:
    type: entity
    table: sb_task
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '64'
        descrip:
            type: string
            length: 128
            nullable: true

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: tasks
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }