Acme\SandboxBundle\Entity\Task:
    type: entity
    table: sb_task
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category:
            type: string
            length: '64'
        name:
            type: string
            length: '64'
        desc:
            type: string
            length: 128
#    manyToOne:
#        category:
#            targetEntity: Category
#            inversedBy: tasks
#            joinColumn:
#                name: category_id
#                referencedColumnName: id
    lifecycleCallbacks: {  }