Panda86\UserBundle\Entity\Employee:
    type: entity
    table: hr_employee
    repositoryClass: Panda86\UserBundle\Entity\EmployeeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128

    oneToMany:
            requests:
                targetEntity: Request
                mappedBy: category
    lifecycleCallbacks: {  }
