Panda86\UserBundle\Entity\Request:
    type: entity
    table: emp_request
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        requestedFor:
            type: string
            length: '64'
        journey_type:
            type: string
            length: '64'
        start_time:
            type: date
            nullable: true
        start_loc:
            type: string
            length: '64'
            nullable: true
        pickup_time:
            type: date
            nullable: true
        pickup_loc:
            type: string
            length: '64'
            nullable: true
        end_time:
            type: date
        end_loc:
            type: string
            length: '64'
        vehicle_type:
            type: string
            length: '16'
        purpose:
            type: string
            length: '64'
        accompaniedBy:
            type: string
            length: '128'
            nullable: true
    lifecycleCallbacks: {  }
