Panda86\UserBundle\Entity\User:
    type: entity
    table: vrm_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
            length: '64'
            nullable: true
        last_name:
            type: string
            length: '64'
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
    oneToOne:
        employee:
          targetEntity: Panda86\AppBundle\Entity\Employee
          joinColumn:
            name: employee_id
            nullable: true
            referencedColumnName: id
    lifecycleCallbacks: {  }
