Panda86\UserBundle\Entity\Vehicle:
    type: entity
    table: hr_vehicle
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '16'
        make:
            type: string
            length: '64'
        model:
            type: string
            length: '64'
        reg_no:
            type: string
            length: '128'
        passenger_no:
            type: integer
        ac:
            type: boolean
            nullable: true
        remarks:
            type: string
            length: '255'
            nullable: true
    lifecycleCallbacks: {  }
